fun main(){
    var array1:IntArray= intArrayOf(10,20,30,50,40,60,70,80,90)
    for(arr in array1)
        println(arr)
    var array2= arrayOf(1,2,3,4,5,6,7,8,9)
    println("arrayof() example")
    for(arr in array2)
        println(arr)
    array1.set(3,40)
    array1.set(4,50)
    println("after prforming set operation")
    for(arr in array1)
        println(arr)
    println("using get operation")
println(array2.get(0))
println(array2.get(1))
println(array2.get(2))
println(array2.get(3))
println(array2.get(4))
println(array2.get(5))
println(array2.get(6))
println(array2.get(7))
println(array2.get(8))
}