fun main(){
    var mutableList1= mutableListOf<String>("Shravani","ruksana")
    var mutableList2= mutableListOf<String>("Kotlin","java","sql")
    var mutableList3= mutableListOf<String>("System","mouse","keyboard")
    println("list of mutablelist1 elements in aseccending")
    for(element in 0..mutableList1.size-1)
        println(mutableList1[element])
    println()
    println("list og mmutableList1 in decending order")
    for(element in mutableList1.size-1..0)
        println(mutableList1[element])
    println()
    println("list if mutableList2 elements")
    for(element in mutableList2)
        println(element)
    println()
    println("list of mutablelist3 elements")
    for(elements in mutableList3)
        println(elements)
    println()
    println("opeartions on mutableList1")
    mutableList1.add("Ranjith")
    println("after adding new element in to list /n $mutableList1")
    mutableList1.add(3,"Rakesh")
    println()
    println("list after adding another element")
    println(mutableList1)
    println()
    println("after removing one element from list")
    mutableList1.remove("shravani")
    println(mutableList1)
    println()
    println("after replacing ruksana with advaith")
    mutableList1.set(0,"advaith")
    println()
    println("adding onel list into another list")
    mutableList1.addAll(4,mutableList2)
    println(mutableList1)
    println()
    println("reaining mutableList1")
    mutableList1.retainAll(mutableList1)
    println(mutableList1)
    println()
    println("removing elemnt from list")
    mutableList1.clear()
    println(mutableList1)
    println()
    println("lilstIteartor function")
    var list=mutableList2.listIterator();
    for(elements in list)
        println(elements)


}